version: "3.8"
services:
  buy-coin-service:
    build: .
    container_name: buy_coin_service
    env_file: .env
    environment:
      API_KEY: ${API_KEY}
      PRIVATE_KEY: ${PRIVATE_KEY}
      COINS: ${COINS}
      STABLE_COIN: ${STABLE_COIN}
      DAILY_AMOUNT: ${DAILY_AMOUNT}
      MONGODB_URL: ${MONGODB_URL}
