name: Deployment

on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Rebuild Image
    runs-on: ubuntu-latest
    steps:
    - name: rebuild docker and rerun service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ./github/tokocrypto-dca
          git pull origin master
          docker-compose build
          docker-compose down
          docker-compose up -d